version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-version-updates:
        patterns:
          - "*"
      all-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
