coverage:
    status:
        project:
            default:
                threshold: 1
                if_ci_failed: error
        patch:
            default:
                threshold: 1
                if_ci_failed: error
comment: false
