matrix:
  include:
  - os: linux
    dist: trusty
    language: python
    python: "3.5"
    env:
      - TWINE_USERNAME="brainiak-bot"
      - secure: "YDzVN9IjAu7kEAPaIDSQi48cGYV8HoQQJpb4ZzGeTA6lfs5OmpQ4QF6Bte7FUpMU5/ibNVaEG+uihk70/3rVCl+hWxSYo7MlvS4viYbZCUE5suQnT0ncasGYYoqdZCroMuTmt4reSn3vThWKPEtURUVac4nb+F0VpNSGhFH9PFwu/7b4Ph37N5ge2KXrjQBEKLc8Q71LlnHASCROjkMcG+6tAOA3kVERInZ/U3gRcjdzekzpLm+YDduKQqSkqNTAus4mNXa5baLGVcq5gvCXZxTntx6GCSBCLbzG8tj8VniCgNkDi6BsQzqdI1rJQI1I7DUxzyIf6OEBoBA/VCl5e+ZxCRGS7mRoMKioQcORLpUGEYF0nY8RrG3C6cxWF9LXqr44HuyYyS8EByn0tjZYgljBEsAxI15FvBibsVpWza9lHksj0sXolBenf6DQCDJlt4V26mbafvRkkJyV2Xcaks7/YfKngxawanRpl5pvzkjl21k7GKWLr3i4gs1Ammbm6Cr3n505Plae/fp+wZCkiHv3GA2cznvPumKaB7VNVWMvr/CClbY5Qe7vY8ZSoChV6V0RSzEW0+h7F+80kCGvA2QhJ4UdiSkYB3+dmGvC2nFLD/TIpjQn8mLbYlRfTwdnbOp1J0eVd+xqPlMY8HmfndYMzmQc8FteNcI7oluZlbU="
      - TWINE_REPOSITORY_URL="https://test.pypi.org/legacy/"
    install:
      - python3 -m pip install -U pip twine
    script:
      - python3 -m pip install -e .
      - python3 setup.py sdist
      - twine upload dist/*
    addons:
      apt:
        packages:
          - build-essential libgomp1 libmpich-dev mpich
