matrix:
  include:
  - os: linux
    dist: trusty
    language: python
    python: "3.5"
    env:
      - TWINE_USERNAME="brainiak-bot"
      - secure: "Ptttm+7EYhN6FiusRQV4lWeAh/48lghaotSvmDw/PLCh69Vqq7YnM6qLS+r+K99qvJLctHj+jPX3TT5xYZhcLD8S5WWq04N2fQyxd23Yr8cL0QeFHE1KeDQqOpcoYW1eMEHx2Xv6YHOrGlQIvi4FCL6T/jEXORfQGwjn4UxCtSU1eP6FLsSdBq3hFnV7hwK9rywzCiWacCahIgiWx6n1qt/Qj3FFbBZmsbBvH1lJdagj1wwCMEwSS57fKq1j1LcJRFzA97jG+mYJHEEAhj6Eyuc7m29hDhFCnbYZ8N+LHBmuSS1zweVgKignBEz2cpEvEtB0eTA/n+SAqbrRPzxYIcHA3wTTz9Cr1HDMNdYox2ZBoWSECPWv+CDrts/s2WFbC8UpClQ67BPctKwQNLuQhf4ztWu2QclDjtND1RBMeoZlwZeCcGhJaDLPtIuiaZRqvh0O8a2Kyq+eJs62zNu/B8VXd6e8WcRdodh4uNc7UOJBwnYk9bmWuP28rATaLIjdFuVtWMlTHO8TyBjqFgeB61SbONBqD7pvv9Oxjrf/wEjifZSoRivoVtfqS231UB+1m2VdI6Ow28G9SOkjaFHkrL/WaoUhWL4oedbpoKwrpWK/qnnFO19J1G5M6p/Zsw7iAiawdkoEU+w01nG/7PdX9DpbLtWghxhd+e3t9WS+9+I="
      - TWINE_REPOSITORY_URL="https://test.pypi.org/legacy/"
    install:
      - python3 -m pip install -U pip twine
    script:
      - python3 -m pip install -e .
      - python3 setup.py sdist
      - twine upload dist/*
    addons:
      apt:
        packages:
          - build-essential libgomp1 libmpich-dev mpich
