matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      language: python
      python: 3.6
      addons: &linux_addons
        apt: &apt
          packages:
            - build-essential libgomp1 libmpich-dev mpich

    - os: linux
      dist: xenial
      sudo: required
      language: python
      python: 3.5
      addons: *linux_addons

    - os: osx
      language: generic
      env: &macos_env
        - CC=/usr/local/opt/llvm/bin/clang
        - CXX=/usr/local/opt/llvm/bin/clang++
        - LDFLAGS="-L/usr/local/opt/llvm/lib
          -Wl,-rpath,/usr/local/opt/llvm/lib $LDFLAGS"
        - CPPFLAGS="-I/usr/local/opt/llvm/include $CPPFLAGS"
        - HOMEBREW_NO_AUTO_UPDATE=1
      before_install: &macos_before_install
        - brew install llvm mpich python3

    # Build and test conda packages
    - os: linux
      dist: xenial
      install: ./.conda/bin/install-miniconda
      script: .conda/bin/build

    - os: osx
      install: ./.conda/bin/install-miniconda
      script: .conda/bin/build
  allow_failures:
    - os: linux
      script: .conda/bin/build

install:
    - python3 -m pip install -U pip codecov

script:
    - ./pr-check.sh
after_success:
    - codecov
