branches:
  only:
    - master

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: 3.4
      addons: &linux_addons
        apt: &apt
          packages:
            - build-essential libgomp1 libmpich-dev mpich

    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: 3.5
      addons: *linux_addons

    - os: osx
      osx_image: xcode7.3
      language: generic
      env: &macos_env
        - CC=/usr/local/opt/llvm/bin/clang
        - CXX=/usr/local/opt/llvm/bin/clang++
        - LDFLAGS="-L/usr/local/opt/llvm/lib
          -Wl,-rpath,/usr/local/opt/llvm/lib $LDFLAGS"
        - CPPFLAGS="-I/usr/local/opt/llvm/include $CPPFLAGS"
        - HOMEBREW_NO_AUTO_UPDATE=1
      before_install: &macos_before_install
        - brew install llvm mpich python3

    - os: osx
      osx_image: xcode8
      language: generic
      env: *macos_env
      before_install: *macos_before_install

    # Build and test conda packages
    - os: linux
      dist: trusty
      env:
        - MINICONDA_URL="https://repo.continuum.io/miniconda"
        - MINICONDA_FILE="Miniconda3-latest-Linux-x86_64.sh"
      install: &install_miniconda
        - curl -L "${MINICONDA_URL}/${MINICONDA_FILE}" -o ~/${MINICONDA_FILE}
        - bash ~/$MINICONDA_FILE -b -u
        - source ~/miniconda3/bin/activate root
        - conda install --yes --quiet conda-build
        - source deactivate
      script: ./.conda/bin/build

    - os: osx
      osx_image: xcode8
      env:
        - MINICONDA_URL="https://repo.continuum.io/miniconda"
        - MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      install: *install_miniconda
      script: ./.conda/bin/build

install:
    - python3 -m pip install -U pip

script:
    - ./pr-check.sh
