#https://travis-ci.org/IntelPNI/brainiak
compiler:
    - gcc
    - clang

branches:
  only:
    - master

matrix:
  allow_failures:
    - os: osx

  include:
    - os: linux
      dist: trusty
      sudo: required
      python: 3.4
      language: python

    - os: linux
      dist: trusty
      sudo: required    
      python: 3.5
      language: python

    - os: osx
      osx_image: xcode7.1
      sudo: required
      language: generic
      env: HINT=Yosemite MPI=openmpi
      before_install:
          - brew update
          - brew install clang-omp
          - brew install python3 


    - os: osx
      osx_image: xcode7.3
      sudo: required
      language: generic
      env: HINT=ElCapitan MPI=openmpi
      before_install:
          - brew update
          - brew install clang-omp
          - brew install python3 

install:
    - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get -y install build-essential cmake libgomp1 mpich2 python3-pip; fi   
    - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then pip3 install -U pip virtualenv; fi   
    - if [[ "$TRAVIS_OS_NAME" != "osx" && "$CXX" = "g++" ]]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake mpich; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CC="clang-omp"; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export export CXX="clang-omp++"; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 install -U pip virtualenv; fi   

script:
    - ./pr-check.sh pr-check

notifications:
  webhooks:
    urls:
      #- https://webhooks.gitter.im/e/4ffabb4df010b70cd624
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always