matrix:
  include:
  - os: linux
    dist: trusty
    language: python
    python: "3.5"
    env:
      - TWINE_USERNAME="brainiak-bot"
      - secure: "HEqZQD3+9qAaFXrwczgTeCyaqiMpzJW2fyyEQh09x2bRsBrkfV5I5nnQLiL9bb8CbFGrYHLqcHAgUElQbneHk3dHuvw0eHy5bpJVMJFqQKKi0ycZscMG5Y5RdE0BIxiQJ6HIGy4crEs6T/TcpScIbtxZA43zUoeYBpp/C8hrAhkgSqUsDvvQVRYK4o/dt4h6EecuqcCUDe5ERF0K78GJx/2x4Yg7uYO6DcFemqo72zxNs24fjYpwU0G0mIznFCc13ZgZu0eJBLq1/LK9QhALj8cCgkVytB/ZzJe6Z7qxQxoVHaSHOs3fPmamGQ5VOLwKlwm4IGjKQ8781nPd3UTHiRtkO+QvXq5nCE1i5Mk9OJSEjFcw98SHeqLJPkOLW9+a2fagsOwM2Y6OPnWrz/Wk7P8tn2WefnHQImmrX1atryCaFOzblIip8PNWA25anxBMs5iSBW/8uSMKA08Hi7HrSVuvqIOC/NC2G6KUt8Yka1yDNkNzkL+i3rOzNeqBbcRkXezsMxEU6Dr4w/9VYpfyscU+pVBuicOsq8n99bDigPwHRPBRMuRwdQczlQXLYhXbQYWY3mtlukyhvIaDJXKaJiJAWKZcsWDx12HnixvbhETzp22cmMadvw5TKLaafBTwoUdTJXCNBD3fxdvZpw3nOmbvH2Phc95ubRVXw77pqpI="
      - TWINE_REPOSITORY_URL="https://test.pypi.org/legacy/"
    install:
      - python3 -m pip install -U pip twine
    script:
      - python3 -m pip install -e .
      - python3 setup.py sdist
      - twine upload dist/*
    addons:
      apt:
        packages:
          - build-essential libgomp1 libmpich-dev mpich
