#https://travis-ci.org/IntelPNI/brainiak
branches:
  only:
    - master

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: 3.4

    - os: linux
      dist: trusty
      sudo: required    
      language: python
      python: 3.5

    - os: osx
      osx_image: xcode7.1
      sudo: required
      language: generic
      env: HINT=Yosemite MPI=mpich
      before_install:
          - brew update
          - brew install python3 

    - os: osx
      osx_image: xcode7.3
      sudo: required
      language: generic
      env: HINT=ElCapitan MPI=mpich
      before_install:
          - brew update
          - brew install python3 

install:
    - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get -y install build-essential cmake libgomp1 mpich2 python3-pip; fi   

    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install llvm mpich; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CC=/usr/local/opt/llvm/bin/clang; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CXX=/usr/local/opt/llvm/bin/clang++; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export LDFLAGS="-L/usr/local/opt/llvm/lib $LDFLAGS"; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CPPFLAGS="-I/usr/local/opt/llvm/include $CPPFLAGS"; fi
    - pip3 install -U pip virtualenv

script:
    - ./pr-check.sh pr-check

notifications:
  webhooks:
    urls:
      #- https://webhooks.gitter.im/e/TOSETUP
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: alwaysfailure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always