[project]
dynamic = ["version"]

[tool.towncrier]
directory = "docs/newsfragments"
package = "brainiak"
template = "docs/newsfragments/_template.jinja"
title_format = "BrainIAK {version} ({project_date})"

    [[tool.towncrier.type]]
    directory = "feature"
    name = "Features"
    showcontent = true

    [[tool.towncrier.type]]
    directory = "bugfix"
    name = "Bugfixes"
    showcontent = true

    [[tool.towncrier.type]]
    directory = "doc"
    name = "Documentation improvements"
    showcontent = true

    [[tool.towncrier.type]]
    directory = "removal"
    name = "Deprecations and removals"
    showcontent = true

[tool.pytest.ini_options]
markers = [
    "notebook: marks example notebook tests",
]

[build-system]
requires = [
    "setuptools>=62", 
    "wheel",
    "pybind11>=2.9.0",
    "scipy!=1.0.0",
    "cython",
    "oldest-supported-numpy",
    "setuptools_scm>=8",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
