package:
  # Repeating name because of the following issue:
  # https://github.com/conda/conda-build/issues/2475
  name: brainiak

  # Can't find a good way to get this from setuptools_scm. This needs to be defined before running conda-build
  version: {{ environ.get('BRAINIAK_VERSION') }}

about:
  home: http://brainiak.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: |
    The Brain Imaging Analysis Kit is a package of Python modules 
    useful for neuroscience, primarily focused on functional 
    Magnetic Resonance Imaging (fMRI) analysis. The package was originally 
    created by a collaboration between Intel and the 
    Princeton Neuroscience Institute (PNI).

source:
  path: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script_env:
    - KMP_DUPLICATE_LIB_OK

  script:
    - PIP_NO_INDEX=False {{ PYTHON }} -m pip install pymanopt
    - {{ PYTHON }} -m pip install . -v

requirements:
  build:
    - python
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - mpich # [not win]
    - llvm-openmp
    - scikit-build-core
    - cmake
    - setuptools_scm>=8.0
    - pybind11>=2.9.0
    - scipy!=1.0.0
    - cython
    - numpy

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - mpi4py>=3
    - nitime
    - scikit-learn>=0.18
    - scipy!=1.0.0
    - statsmodels
    - psutil
    - nibabel
    - joblib
    - wheel
    - pydicom
    - tensorflow  # [not win]
    - tensorflow-probability # [not win]

test:
  source_files:
    - tests
    - pyproject.toml
  imports:
    - brainiak
  commands:
    - pytest
  requires:
    - pytest
    - testbook
    - numdifftools
    - pytest-reportlog
