package:
  # Repeating name because of the following issue:
  # https://github.com/conda/conda-build/issues/2475
  name: brainiak

  # Can't find a good way to get this from setuptools_scm. This needs to be defined before running conda-build
  version: {{ environ.get('BRAINIAK_VERSION') }}

about:
  home: http://brainiak.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: |
    The Brain Imaging Analysis Kit is a package of Python modules 
    useful for neuroscience, primarily focused on functional 
    Magnetic Resonance Imaging (fMRI) analysis. The package was originally 
    created by a collaboration between Intel and the 
    Princeton Neuroscience Institute (PNI).

source:
  path: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script_env:

    # We need the source directory because conda removes source / working
    # directories by the time we reach the test phase. We can optionally pass in
    # the --keep-old-work flag later on to use the $PREFIX/work directory
    - BRAINIAK_HOME
    - MKL_THREADING_LAYER
    - KMP_DUPLICATE_LIB_OK

  script:
    - {{ PYTHON }} -m pip install . -v

requirements:
  build:
    - python
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - mpich
    - llvm-openmp
    - scikit-build-core
    - cmake
    - setuptools_scm>=8.0
    - pybind11>=2.9.0
    - scipy!=1.0.0
    - cython

  run:
    - python
    - numpy
    - mpi4py>=3
    - nitime
    - scikit-learn>=0.18
    - scipy!=1.0.0
    - statsmodels
    - psutil
    - nibabel
    - joblib
    - wheel
    - pydicom
    - tensorflow

test:
  source_files:
    - tests
    - pyproject.toml
  imports:
    - brainiak
  commands:
    - pytest
    - conda inspect linkages -p $PREFIX brainiak  # [not win]
    - conda inspect objects -p $PREFIX brainiak  # [osx]
  requires:
    - pytest
    - testbook
    - numdifftools
    - pytest-reportlog
