on: [pull_request]
jobs:
  notebook_tests:
    env:
      IGNORE_CONDA: false
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          chmod a+x pr-check.sh
          ./pr-check.sh
