on: [pull_request]
jobs:
  pypi:
    env:
      IGNORE_CONDA: true
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          chmod a+x pr-check.sh
          ./pr-check.sh
