on:
  pull_request:
  push:
  release:
    types:
      - published


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pypi:
    env:
      IGNORE_CONDA: true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: mpi4py/setup-mpi@v1
      - run: |
          python3 -m pip install -U pip
      - if: ${{ contains(matrix.os, 'ubuntu') }}
        run: |
          ./pr-check.sh
      - if: ${{ contains(matrix.os, 'macos') }}
        run: |
          export CLANG_PREFIX=$(brew --prefix llvm@15)
          export CC=$CLANG_PREFIX/bin/clang
          export CXX=$CLANG_PREFIX/bin/clang++
          export LDFLAGS="-L$CLANG_PREFIX/lib
          -Wl,-rpath,$CLANG_PREFIX/lib $LDFLAGS -L/usr/local/opt/libomp/lib"
          export CPPFLAGS="-I$CLANG_PREFIX/include $CPPFLAGS -I/usr/local/opt/libomp/include"
          ./pr-check.sh
      - uses: codecov/codecov-action@v1
  conda:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v2
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: test-env
          create-args: >-
            python=${{ matrix.python-version }}
            boa
      - run: |
          export CONDA_HOME=$CONDA
          conda install conda-build
          out_dir=`mktemp -d -t compilation-XXXXXXXXXX`
          .conda/bin/build ${{ matrix.python-version }} $out_dir
          package_path=`find $out_dir -name "*.tar.bz2"`
          echo "Package path: ${package_path}"
      - uses: actions/upload-artifact@v3
        with:
          path: ${{env.package_path}}
  